version: "3.8"

services:
  app:
    build: .
    container_name: url_shortener
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASS=${REDIS_PASS}
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis_instance
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
